/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type{ CreateReservationRequest } from './models/create-reservation-request';
export type { CreateUserRequest } from './models/create-user-request';
export type { CreateVehicleRequest } from './models/create-vehicle-request';
export type { GrantedAuthority } from './models/granted-authority';
export type { LoginUserRequest } from './models/login-user-request';
export type { ReservationResponse } from './models/reservation-response';
export type { ReservationStatisticsResponse } from './models/reservation-statistics-response';
export type { UpdateUserRequest } from './models/update-user-request';
export type { UpdateVehicleRequest } from './models/update-vehicle-request';
export type { UserEntity } from './models/user-entity';
export type { VehicleEntity } from './models/vehicle-entity';
