/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { CreateReservationRequest } from './models/create-reservation-request';
export { CreateUserRequest } from './models/create-user-request';
export { CreateVehicleRequest } from './models/create-vehicle-request';
export { GrantedAuthority } from './models/granted-authority';
export { LoginUserRequest } from './models/login-user-request';
export { ReservationResponse } from './models/reservation-response';
export { ReservationStatisticsResponse } from './models/reservation-statistics-response';
export { UpdateUserRequest } from './models/update-user-request';
export { UpdateVehicleRequest } from './models/update-vehicle-request';
export { UserEntity } from './models/user-entity';
export { VehicleEntity } from './models/vehicle-entity';
