/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReservationStatisticsResponse {
  count?: number;
  month?: string;
  profit?: number;
  status?: string;
  year?: number;
}
