/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateReservationRequest {
  endDate: string;
  startDate: string;
  vehicleId?: number;
}
