/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateVehicleRequest {
  color?: string;
  dailyFee?: number;
  model?: string;
  vehicleStatus?: 'AVAILABLE' | 'MAINTENANCE';
}
