/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VehicleResponse {
  brand?: string;
  color?: string;
  dailyFee?: number;
  fuelType?: 'DIESEL' | 'PETROL' | 'ELECTRIC';
  gearboxType?: 'AUTOMATIC' | 'MANUAL';
  id?: number;
  imagePath?: string;
  model?: string;
  vehicleStatus?: 'AVAILABLE' | 'MAINTENANCE';
  year?: number;
}
