/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateVehicleRequest } from '../../models/update-vehicle-request';
import { VehicleEntity } from '../../models/vehicle-entity';

export interface UpdateVehicle$Params {
  id: number;
      body: UpdateVehicleRequest
}

export function updateVehicle(http: HttpClient, rootUrl: string, params: UpdateVehicle$Params, context?: HttpContext): Observable<StrictHttpResponse<VehicleEntity>> {
  const rb = new RequestBuilder(rootUrl, updateVehicle.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VehicleEntity>;
    })
  );
}

updateVehicle.PATH = '/api/vehicles/{id}';
