/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReservationResponse } from '../../models/reservation-response';

export interface ListOfActiveOrFutureReservations$Params {
  id: number;
}

export function listOfActiveOrFutureReservations(http: HttpClient, rootUrl: string, params: ListOfActiveOrFutureReservations$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReservationResponse>>> {
  const rb = new RequestBuilder(rootUrl, listOfActiveOrFutureReservations.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ReservationResponse>>;
    })
  );
}

listOfActiveOrFutureReservations.PATH = '/api/reservations/vehicle-reservations/{id}';
