/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VehicleEntity } from '../../models/vehicle-entity';

export interface GetAllVehicles$Params {
}

export function getAllVehicles(http: HttpClient, rootUrl: string, params?: GetAllVehicles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<VehicleEntity>>> {
  const rb = new RequestBuilder(rootUrl, getAllVehicles.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<VehicleEntity>>;
    })
  );
}

getAllVehicles.PATH = '/api/vehicles';
