/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUserRequest {
  age?: number;
  email?: string;
  name?: string;
  password?: string;
  surname?: string;
  userType?: 'ADMIN' | 'USER';
  username?: string;
}
