/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReservationResponse {
  duration?: number;
  endDate?: string;
  price?: number;
  reservationId?: number;
  startDate?: string;
  status?: string;
  userId?: number;
  vehicleId?: number;
  vehicleName?: string;
}
