/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GrantedAuthority } from '../models/granted-authority';
export interface UserEntity {
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  age?: number;
  authorities?: Array<GrantedAuthority>;
  createdAt?: string;
  credentialsNonExpired?: boolean;
  deletedAt?: string;
  email?: string;
  enabled?: boolean;
  id?: number;
  name?: string;
  password?: string;
  surname?: string;
  updatedAt?: string;
  userType?: 'ADMIN' | 'USER';
  username?: string;
}
